### ISSUE TITLE
No module named 'debtcollerctor'

### ISSUE THREAD

**Issue by MelvinYYY** [Mishima-syk/psikit#19]
Hi @iwatobipen @kzfm,

I'm trying to learn how to use this module but when I import the module it returns an exception: No module named 'debtcollerctor'. Should the module be ‘debtcollector'’? 

Thanks,

Melvin

**Comment by kzfm** [comment]
Hi MelvinYYY,

Thank you for noticing it, It was the typo and I fixed it. But you may need to install that module by typing "conda install -c conda-forge debtcollector ".

**Comment by MelvinYYY** [comment]
Thank you!
