### ISSUE TITLE
Adding a function to use the mol generate by the RDKit?

### ISSUE THREAD

**Issue by MelvinYYY** [Mishima-syk/psikit#20]
Hi there,

I think it would be great if you can add a function to use mol object generated by the RDKit in the global environment. 

I'm currently using this git to get mol objects from the xyz file. https://raw.githubusercontent.com/jensengroup/xyz2mol/master/xyz2mol.py

If I convert the mol to smile or mol_file and then load into the pk class, some information seem got loss or distorted. 

I'm wondering if you guys can work on a function to use the mol object in the global environment directly? 

Thanks,

Melvin

**Comment by kzfm** [comment]
HI Melvin,

you can add your RDKit mol object to pk class

    pk = Psikit()
    pk.mol = your_mol_object

Is this the answer to your question?

Best regards,

kzfm

**Comment by MelvinYYY** [comment]
I see. Thank you.

**Comment by kzfm** [comment]
You're welcome.
