### ISSUE TITLE
ResourceWarning: unclosed file

### ISSUE THREAD

**Issue by kzfm** [Mishima-syk/psikit#23]
When I calculated the dipole moments of molecules in for statement, I got many these warnings.

> /home/ohkawa/anaconda3/lib/python3.6/site-packages/psi4/driver/qcdb/libmintsbasisset.py:854: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/ohkawa/anaconda3/share/psi4/basis/sto-3g.gbs' mode='r' encoding='UTF-8'>
> names[index] = parser.load_file(fullfilename) 

How can I fix it?

**Comment by iwatobipen** [comment]
This is just warning, it is because psi4 code doesn't call close method after open the basis file.
https://github.com/psi4/psi4/blob/master/psi4/driver/qcdb/libmintsbasissetparser.py#L73
The message will be gone if you insert infile.close() before return statement.
Thanks.

**Comment by kzfm** [comment]
Ignore warnings
