### ISSUE TITLE
ImportError: cannot import name 'Sapt' from 'psikit' 

### ISSUE THREAD

**Issue by kzfm** [Mishima-syk/psikit#28]
============================================================= ERRORS =============================================================
______________________________________________ ERROR collecting tests/test_init.py _______________________________________________
ImportError while importing test module '/Users/kzfm/python/psikit/tests/test_init.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_init.py:2: in <module>
    from psikit import Sapt
E   ImportError: cannot import name 'Sapt' from 'psikit' (/Users/kzfm/anaconda3/lib/python3.7/site-packages/psikit/__init__.py)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
==================================================== 1 error in 0.91 seconds =====================================================

**Comment by kzfm** [comment]
The test import psikit from anaconda3/lib/python3.7/site-packages/psikit which cause the error. You should import it from the relative directory.

I tried .psikit or ..psikit but it didn't work

**Comment by iwatobipen** [comment]
Thanks for your comment.
I will fix the issue ASAP.

**Comment by kzfm** [comment]
I added the psikit dir into sys.path.

```
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
```
