### ISSUE TITLE
dipolemoment calculation failed for the deprecation of the get_variable() function

### ISSUE THREAD

**Issue by wangyingxie** [Mishima-syk/psikit#43]

**Comment by iwatobipen** [comment]
Hi,
Thanks for your issue.
I just updated psikit in dev branch.
Could you please use the branch to calculate dipolemoment?
The version of psi4 should be >= 1.4.
Thanks,
Taka

**Comment by wangyingxie** [comment]
Thanks for the correction, I have also updated like this, this also works

    @property
    def dipolemoment(self, basis_sets= "b3lyp/6-311pg**", return_wfn=True):
        #  The three components of the SCF dipole [Debye]
        x = self.psi4.variable('SCF DIPOLE')[0]
        y = self.psi4.variable('SCF DIPOLE')[1]
        z = self.psi4.variable('SCF DIPOLE')[2]
        total = np.sqrt(x * x + y * y + z * z)
        return (x, y, z, total)
