### ISSUE TITLE
There is no description about license

### ISSUE THREAD

**Issue by iwatobipen** [Mishima-syk/psikit#8]

**Comment by kzfm** [comment]
RDKit: Business-friendly BSD license
https://github.com/rdkit/rdkit/blob/master/license.txt

Psi4: LGPL-3.0.
http://www.psicode.org/psi4manual/1.2/introduction.html#license

**Comment by kzfm** [comment]
https://mag.osdn.jp/06/06/09/1537222

**Comment by kzfm** [comment]
Added LICENSE(BSD-3)
